# Alembic migration script template.
"""add resumes table

Revision ID: 1c9c5cecd0c8
Revises: 4f2fd9157eef
Create Date: 2026-02-06 06:31:42.445176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9c5cecd0c8'
down_revision: Union[str, Sequence[str], None] = '4f2fd9157eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
