# Alembic migration script template.
"""add first and last name to users

Revision ID: 4f2fd9157eef
Revises: 64a33323b749
Create Date: 2026-02-06 05:43:53.882485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2fd9157eef'
down_revision: Union[str, Sequence[str], None] = '64a33323b749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns with temporary defaults so existing rows do not fail
    op.add_column(
        'users',
        sa.Column('first_name', sa.String(), nullable=False, server_default='')
    )
    op.add_column(
        'users',
        sa.Column('last_name', sa.String(), nullable=False, server_default='')
    )
    op.add_column(
        'users',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true())
    )

    # Remove defaults so new rows must explicitly provide values
    op.alter_column('users', 'first_name', server_default=None)
    op.alter_column('users', 'last_name', server_default=None)
    op.alter_column('users', 'is_active', server_default=None)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
