# Alembic migration script template.
"""add job applications

Revision ID: c0ac65803fd2
Revises: 1c9c5cecd0c8
Create Date: 2026-02-06 20:00:55.698757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0ac65803fd2'
down_revision: Union[str, Sequence[str], None] = '1c9c5cecd0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('job_description', sa.Text(), nullable=True))
    op.alter_column('job_applications', 'resume_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('job_applications_resume_id_fkey'), 'job_applications', type_='foreignkey')
    op.drop_constraint(op.f('job_applications_user_id_fkey'), 'job_applications', type_='foreignkey')
    op.create_foreign_key(None, 'job_applications', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'job_applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.create_foreign_key(op.f('job_applications_user_id_fkey'), 'job_applications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('job_applications_resume_id_fkey'), 'job_applications', 'resumes', ['resume_id'], ['id'])
    op.alter_column('job_applications', 'resume_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('job_applications', 'job_description')
    # ### end Alembic commands ###
